export const APIS = {
  SPEECH_RECOGNITION: {
    WEB_SPEECH_API: 'WEB_SPEECH_API',
  },
  SPEECH_SYNTHESIS: {
    WEB_SPEECH_API: 'WEB_SPEECH_API',
    AI_TALK: 'AI_TALK'
  }
};

export const CHARACTER_STATUS = {
  NORMAL: 'NORMAL',
  LISTENING: 'LISTENING',
  SPEAKING: {
    NORMAL: 'SPEAKING-NORMAL',
    SMILE: 'SPEAKING-SMILE',
  },
  SMILE: 'SMILE',
  TROUBLED: 'TROUBLED',
  ANALYZING: 'ANALYZING',
  OJIGI: 'OJIGI',
  LEFT: 'LEFT',
  RIGHT: 'RIGHT',
};

export const FACE_DETECTION = {
  DETECTED: 'DETECTED',
  LOST: 'LOST',
};